version: '3'

networks:
  uni_networks:
    external: false
  traefik_public:
    external: true

volumes:
  uni:
    driver: local
  postgres_db:
    driver: local

services:
  uni:
    image: "ghcr.io/aleksandr-poliakov/university/uni-be"
    networks:
      - uni_networks
      - traefik_public
    environment:
      - DB_URL=jdbc:postgresql://db:32770/university
      - DB_USER=postgres
      - DB_PASS=postgres
      - PORT=8080
      - PROFILE=default
      - CONTEXT_PATH=
      - APP_URL=https://staging.university.ro
      - BE_URL=https://test-api.university.ro
      - REGISTER_CONFIRM_EMAIL=TRUE
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.uni-bc-dev.rule=Host(`test-${APP_HOST}`)"
        - "traefik.http.services.uni-bc-dev.loadbalancer.server.port=8080"
        - "traefik.http.routers.uni-bc-dev.tls=true"
        - "traefik.http.routers.uni-bc-dev.tls.certresolver=hetzner"
      placement:
        constraints:
          - node.labels.worker == worker1

  db:
    image: postgres:13
    networks:
      - uni_networks
    environment:
      - POSTGRES_DB=university
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker1
