version: '3'

networks:
  uni_networks:
    external: false

volumes:
  uni:
    driver: local
  postgres_db:
    driver: local

services:
  uni:
    image: uni:latest
    ports:
      - 8080:8080
    networks:
      - uni_networks
    environment:
      - DB_URL=jdbc:postgresql://db:32770/university
      - DB_USER=postgres
      - DB_PASS=postgres

      - PORT=8080
      - PROFILE=default
      - CONTEXT_PATH=/uni
      - APP_URL=http://localhost:32770
      - REGISTER_CONFIRM_EMAIL=TRUE

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    networks:
      - imo_networks
    environment:
      - POSTGRES_DB=university
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - postgres_db:/var/lib/postgresql/data
