name: Deploy on develop

on:
  pull_request_target:
    branches: [ "develop" ]
    types:
      - closed
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Test
        run: |
          mvn test
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build docker image with maven
        run: |
          mvn clean install -U
          mvn package spring-boot:build-image -Dspring-boot.build-image.imageName=university/uni-be
      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker create and push image
        run: |
          IMAGE_ID=ghcr.io/${{ secrets.OWNER }}/university/uni-be
          VERSION=dev-${GITHUB_RUN_NUMBER}
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker build -t university/uni-be .
          docker tag university/uni-be $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: copy file university-dev.yaml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "university-dev.yaml"
          target: "/root"

      - name: set env and deploy
        uses: appleboy/ssh-action@master
        env:
          APP_HOST: ${{ secrets.APP_HOST }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: APP_HOST,GITHUB_RUN_NUMBER
          script: |
            VERSION=dev-${GITHUB_RUN_NUMBER}
            echo "" > ENV_FILE_RE
            echo "IMAGE_TAG=$VERSION" >> ENV_FILE_RE
            echo "APP_HOST=$APP_HOST" >> ENV_FILE_RE
            export $(xargs < ENV_FILE_RE)
            docker stack deploy --with-registry-auth -c university-dev.yaml university-dev
